### ISSUE TITLE
Safari and Chrome Notifications

### ISSUE THREAD

**Issue by gio82** [jleclanche/django-push-notifications#157]
It would be very useful to implement Safari and Chrome Push Notifications (server side only).
I'm still not expert but they should be quite similar to iOS and Android notifications respectively.

**Comment by jleclanche** [comment]
I'm willing to take PRs implementing it.

**Comment by jamaalscarlett** [comment]
I don't know about Safari, but chrome notifications work with minimal changes.  I had to use https://github.com/ottoyiu/django-cors-headers because of cross-domain communication protections built into the browser.  Registering devices and sending messages is identical on chrome and android.
See https://developers.google.com/cloud-messaging/chrome/client to start and https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/gcm-notifications for a sample chrome extension.  If you try and implement this, **chrome://gcm-internals** is your best friend.  It provides in browser logging for all gcm communication to your chrome instance.

**Comment by jleclanche** [comment]
Closing as dupe of #276
