### ISSUE TITLE
Work with custom User model

### ISSUE THREAD

**Issue by Gocht** [jleclanche/django-push-notifications#198]
How can I change the FK from auth.User to a custom User model?

**Comment by jamaalscarlett** [comment]
In models.py, import your custom model and then change the user attribute in the device model to reference your custom user model.

**Comment by jleclanche** [comment]
The user model is used as `AUTH_USER_MODEL` so that setting is automatically taken into account.

**Comment by AndreasBackx** [comment]
Wouldn't it be better to remove fields like name, activate, user and date_created from the Device model? I feel like because this is a library, the developer himself should implement these features how he wants to implement them. The library could provide a backward compatible model for this which at the same time could provide a simple starting solution and example.

Perhaps the user could then provide his own subclass of Device in the settings if he so desires. I'm willing to help out with this.

**Comment by fsto** [comment]
I completely agree with @AndreasBackx.

**Comment by AndreasBackx** [comment]
@fsto see #234

**Comment by fsto** [comment]
Thanks @AndreasBackx, I submitted a PR (#278) which lets users optinally define their own `USER_MODEL` in the `PUSH_NOTIFICATIONS_SETTINGS`.
