### ISSUE TITLE
Is there MAX # for apns?

### ISSUE THREAD

**Issue by pcompassion** [jleclanche/django-push-notifications#204]
Doc says, "If the registration_ids list is larger than that number, multiple bulk messages will be sent." for GCM.

How does django-registration handle arbitrary large APNS devices when sending bulk message?

**Comment by Alp-Phone** [comment]
I assume you meant to ask:
>How does ```django-push-notifications``` handle arbitrary large APNS devices when sending bulk message?

As far as I understand the protocol, you can send any number of messages once the APNS connection has been established.  The problem is how the APNS interface handles malformed messages, which is abysmal, IMHO.

From the [docs:](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW1)
> If you send a notification that is malformed or otherwise unintelligible, APNs returns an error-response packet and closes the connection. Any notifications that you sent after the malformed notification using the same connection are discarded, and must be resent.

All of this nonsense will hopefully go away with the new APNS interface. https://github.com/jleclanche/django-push-notifications/issues/170
