### ISSUE TITLE
Code style revolution

### ISSUE THREAD

**Issue by koutoftimer** [jleclanche/django-push-notifications#239]
Issue was created according to quote from [google+ post][1]

> but I do wish more programmers would consider more concrete arguments than "I have it the way I like it" for indent.﻿

## Library

Library is code reused a lot of times, by different people, which means code should be readable for most of users. If we are talking about python we have only one code style understandable by all language users [PEP8][2].

> One of Guido's key insights is that code is read much more often than it is written. The guidelines provided here are intended to improve the readability of code and make it consistent across the wide spectrum of Python code. As PEP 20 says, "Readability counts".
A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is most important.

**Summary:** we should follow PEP8.

## Indentation

Let's assume we are using tab indentations with editor setting: replace tab visual with 4 spaces and we writing following code

    def function_with_too_much_parameters(first, second, third=None, forth=None,
                                        fifth=None, sixth=None):
        pass

According to PEP8 you have to align code with opening delimiter, but how to do that with tabs? With spaces it will look like:

    def function_with_too_much_parameters(first, second, third=None, forth=None,
                                          fifth=None, sixth=None):
        pass

It is not possible to make such look with tabs because they can give you only indentations divisible by 4.

What about mixing use of tabs with spaces for such cases? Quote from [PEP8][3]

> Python 3 disallows mixing the use of tabs and spaces for indentation.

**Summary:** we should use 4 space indentation.

## Maximum line width

According to [PEP8][4]

> Limiting the required editor window width makes it possible to have several files open side-by-side, and works well when using code review tools that present the two versions in adjacent columns.

and this is true. I and lots of people usually use splitting feature. Most valuable it is for merging or resolving git conflicts, when you have not 2 but 3 columns and can compare code without memorizing.

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters.

I was member of such team and you know, we are all using restriction 80 characters per line now. Why? Because when you write code it is not hard to read long line, it looks even better then few short, but when you will read it after week or two... short lines much better. Also if you write long line it means that, probably something is wrong and you should stop writing code and think little bit longer. It is not my opinion, it is my and others people experience in using different maximum line width.

> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

**Summary:** we should use maximum line width 80 characters.

## Imports

According to [PEP8][5]

> Imports should be grouped in the following order:
1. standard library imports
2. related third party imports
3. local application/library specific imports

In addition I would like to add, that they should be sorted in alphabet order as it is much faster to find required with lots of dependencies. Currently can be applied only for tests, as they have biggest import section.

**Summary:** managing imports by hands will improve readability.

   [1]: https://plus.google.com/+JeromeLeclanche/posts/bz88s4ZQxNp
   [2]: https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds
   [3]: https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces
   [4]: https://www.python.org/dev/peps/pep-0008/#maximum-line-length
   [5]: https://www.python.org/dev/peps/pep-0008/#imports

**Comment by jleclanche** [comment]
I'm not sure what you're suggesting here. Are you actually suggesting to revamp the codestyle? Or is this just your general take on it?

If the former, the answer is no. You may disagree with some of the decisions taken in the code style, but it's consistent and readable, which is what actually matters. Changing the code style, which can introduce bugs and is nearly impossible to actually review, is a task you should never, ever do for theoretical reasons.

If the latter, well I don't know why you bring up imports since I already follow pep8 there (and if I don't, feel free to PR a fix, those are harmless). Your argument on maximum line length is extremely weak, boiling down to "I think 80 characters looks better than 100 characters" - I think 90-100 characters looks perfect and I have been writing a *lot* of python code for a fairly long time now, so it comes down to taste.

As for indentation, I never write code like what you demonstrated. First of all, function names should be terse and their parameters should be to the point - a function with parameter overflow is a symptom of a design issue. But if you do somehow end up with overflowing parameters, you simply write it like so:

```
def function_with_many_parameters(first, second, third, fourth, fifth,
	fifth, sixth, ...):
	pass
```

Again, symptoms.
