### ISSUE TITLE
SSLEOFError

### ISSUE THREAD

**Issue by nikilster** [jleclanche/django-push-notifications#274]
Still seeing a lot of these crop up.  Really important to get these fixed or we have to figure out another way to send pushes.

We have api calls send a lot ~50-100 pushes in a row in 1 call.  Getting a lot of these SSL EOF Errors.  Any ideas?

**Comment by ntuanhnd** [comment]
I meet that problem too, still finding solution.

**Comment by williamfligor** [comment]
I am having the same issue, with every push I try to make.

**Comment by chrisballinger** [comment]
Try regenerating your push certificate using the new Production+Development option

**Comment by williamfligor** [comment]
@chrisballinger thanks. We regenerated our push certificates and got it to push without error. Can't figure out why notifications aren't showing up on the devices, but that's probably unrelated to this project.

**Comment by chrisballinger** [comment]
@williamfligor Double-check that you're sending to the correct endpoint e.g. production vs sandbox

**Comment by evdoks** [comment]
@williamfligor Or make sure that you are sending to correct APNS ids. We experience similar issues when sending a push at too many devices with APNS ids not corresponding to the APNS Certificate. E.g., it happens when developers are register devices compiled agains sandbox endpoint at the production backend. In this case Apple seems to be thinking a DoS attack is launched and breaks the connection (at least this is what I've heard from others) The way to circumvent is is to reduce the size of the APNS batch, so that APNS returns normal errors which allow to remove invalid APNS ids. After that the chunk size can be set back to the original number.

**Comment by jleclanche** [comment]
This doesn't appear to be a bug in DPN.
