### ISSUE TITLE
Using app without default django User model

### ISSUE THREAD

**Issue by skkap** [jleclanche/django-push-notifications#385]
I am not using Django admin or standard User subsystem of Django. 
Apparently Device model has FK field to auth.User, which I dont have.
I get this error:

```
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
ERRORS:
push_notifications.APNSDevice.user: (fields.E300) Field defines a relation with model 'auth.User', which is either not installed, or is abstract.
push_notifications.APNSDevice.user: (fields.E307) The field push_notifications.APNSDevice.user was declared with a lazy reference to 'auth.user', but app 'auth' isn't installed.
push_notifications.GCMDevice.user: (fields.E300) Field defines a relation with model 'auth.User', which is either not installed, or is abstract.
```

If it is possible, I would like to turn of all models of this app and store Notification Keys of devices myself and use this app just for sending.
What can I do?

**Comment by matthewh** [comment]
@skkap You can customize the model used for the user model and set it to some other model in your django app.

```
PUSH_NOTIFICATIONS_SETTINGS = {
        "USER_MODEL": "your_app.another_model",
        ...
}
```

This project is designed to be used with Django's ORM. We plan, though not in the near term, to allow all of the device models (APNSDevice, GCMDevice, WNSDevice) to be extended or replaced though that is not possible right now. Since you are handling the storage of device information already, I suggest selecting libraries that that focus on sending push notifications. Like https://github.com/Pr0Ger/PyAPNs2.

**Comment by skkap** [comment]
Thanks for reply! Helped a lot!

**Comment by matthewh** [comment]
@skkap Good luck with your project.
