### ISSUE TITLE
Send bulk message working but messages are not delivered

### ISSUE THREAD

**Issue by tyapkov** [jleclanche/django-push-notifications#392]
When sending bulk message to GCM devices from admin I get that "All messages were sent". At the same time when I am login in GCM console, I don't see any requests to the API. Also messages are not delivered to the devices. 

Are test messages actually delivered? How can I test delivery?

**Comment by jamaalscarlett** [comment]
@tyapkov If you are receiving the success message, the problem is not with this package.  The success message means that the request was received by the GCM/FCM server.  That you did not receive the message on the device could be for any number of reasons.  FCM allows you to send messages directly from the console.  I would make sure that that works first.
