### ISSUE TITLE
Dropped support for Django 1.8?

### ISSUE THREAD

**Issue by gabn88** [jleclanche/django-push-notifications#411]
Is there any reason to drop support Django 1.8? It is a LTS, meaning that it is in (production) use until (at least) april 2018...

see https://www.djangoproject.com/download/

**Comment by jleclanche** [comment]
Well, just because it's supported upstream doesn't mean it has to be supported downstream :)

Django 1.8 is kinda ancient; if you want to keep using it, I think it's okay to use older versions of libraries. I highly recommend moving over to 1.11 which is also an LTS and is more likely to be supported a fairly long time.

**Comment by gabn88** [comment]
So what is the last release working under Django 1.8? I would recommend not dropping support until it is necessary (because of too much boilerplate). But of course it is your package, so you decide :)

**Comment by jleclanche** [comment]
1.4.1. Knowing that there are other fairly high traffic django packages out there dropping support for 1.8 in favour of 1.11, I feel comfortable dropping it here (this library comparatively isnt that popular!)
